
require "user.comment"
require "user.telescope"
require "user.plugins"
require "user.lualine"
require "user.colorscheme"
require "user.nvim-tree"
require "user.keymaps"
require "user.options"
require "user.whichkey"
require "user.undotree"
require "user.bufferline"
require "user.toggleterm"
require "user.surround"
require "user.treesitter"
